# ETL-pipeline/config/config.yaml
use_bbox_filter: true  # Set to true to enable BBOX filtering for REST APIs
logging_level: "INFO" # Changed from VERBOSE for less noise in this example
max_retries: 3
continue_on_failure: true

# Optional: Define a global BBOX here if use_bbox_filter is true
# These would be used if a source of type 'rest_api' doesn't define its own bbox in sources.yaml
#global_ogc_bbox_coords: "586206,6551160,647910,6610992"  # Your SWEREF99 coords
# Use WGS84 coordinates instead of SWEREF99
global_ogc_bbox_coords: "16.5008129,59.0906713,17.6220373,59.6050281"
global_ogc_bbox_crs_uri: "CRS84"  # or "4326"
ogc_api_delay: 0.1  # Seconds between requests (default: 0.1)

# Geoprocessing settings
geoprocessing:
  enabled: true
  aoi_boundary: "data/connections/municipality_boundary.shp"
  target_srid: 3010
  parallel_processing_factor: "100"
  cleanup_intermediate: true  # Remove processed GDBs after SDE load

  
# Optional: Source-specific SDE overrides
source_overrides:
  - name: "Riksintressen"
    authority: "LST" 
    sde_dataset: "PLANNING"
    sde_fc: "national_interests"


# SDE connection settings
sde_connection_file: "data/connections/prod.sde"
sde_schema: "GNG"  # Schema prefix for datasets
sde_load_strategy: "truncate_and_load"  # Options: "truncate_and_load", "replace", "append"