# ETL-pipeline/config/config.yaml
use_bbox_filter: true  # Set to true to enable BBOX filtering for REST APIs
logging_level: "INFO" # Changed from VERBOSE for less noise in this example
max_retries: 3
continue_on_failure: true

# Optional: Define a global BBOX here if use_bbox_filter is true
# These would be used if a source of type 'rest_api' doesn't define its own bbox in sources.yaml
global_bbox: "586206,6551160,647910,6610992"
global_bbox_sr: "3006"