# ETL Pipeline Global Configuration
# This is the main configuration file for the ETL pipeline

# Environment settings (can be overridden by ETL_ENVIRONMENT variable)
environment: "development"  # Options: development, staging, production
debug: false

# Logging configuration
logging:
  level: "INFO"
  console_level: "INFO"
  summary_file: "etl_summary.log"
  debug_file: "etl_debug.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_file_size_mb: 10
  backup_count: 5

# Retry and resilience configuration
retry:
  max_attempts: 3
  base_delay: 1.0
  backoff_factor: 2.0
  max_delay: 300.0
  timeout: 30
  circuit_breaker_threshold: 5
  circuit_breaker_timeout: 60.0

# File paths configuration
paths:
  download: "downloads"
  staging: "staging"
  output: "output"
  temp: "temp"
  logs: "logs"

# Data processing configuration
processing:
  chunk_size: 1000
  parallel_workers: 2
  memory_limit_mb: 1024
  enable_caching: true
  cache_ttl_hours: 24

# Data validation configuration
validation:
  strict_mode: false
  schema_validation: true
  geometry_validation: true
  attribute_validation: true
  coordinate_system_validation: true
  max_validation_errors: 100

# Security configuration
security:
  enable_ssl_verification: true
  trusted_hosts: []
  max_file_size_mb: 1024
  allowed_file_types:
    - ".zip"
    - ".gpkg"
    - ".shp"
    - ".geojson"
    - ".json"
    - ".gdb"

# Database configuration
database:
  connection_string: null
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30
  echo_sql: false

# Legacy compatibility settings
use_bbox_filter: true  # Set to true to enable BBOX filtering for REST APIs
continue_on_failure: true

# Optional: Define a global BBOX here if use_bbox_filter is true
# These would be used if a source of type 'rest_api' doesn't define its own bbox in sources.yaml
global_ogc_bbox_coords: "16.5008129,59.0906713,17.6220373,59.6050281"
global_ogc_bbox_crs_uri: "CRS84"  # or "4326"
ogc_api_delay: 0.1  # Seconds between requests (default: 0.1)

# SDE loading settings
sde_connection_file: "data/connections/prod.sde"
sde_schema: "GNG"  # Schema prefix for datasets
sde_dataset_pattern: "Underlag_{authority}"  # Pattern for dataset names
sde_load_strategy: "truncate_and_load"  # Options: "truncate_and_load", "replace", "append"

# Geoprocessing settings
geoprocessing:
  enabled: true
  aoi_boundary: "data/connections/municipality_boundary.shp"
  target_srid: 3010
  parallel_processing_factor: "100"
  cleanup_intermediate: true  # Remove processed GDBs after SDE load

# Optional: Source-specific SDE overrides
# source_overrides:
#   - name: "Riksintressen"
#     authority: "LST" 
#     sde_dataset: "LST"
#     sde_fc: "Riksintressen"
#     sde_schema: "GNG"  # Optional, defaults to GNG

# Handle potential duplicates in existing datasets
sde_duplicate_handling: "warn_and_proceed"  # Options: "warn_and_proceed", "fail_on_duplicates", "ignore"

# Authority to dataset mapping (overrides pattern for special cases)
sde_authority_mapping:
  LSTD: "GNG.Underlag_LstD"  # Special case: LSTD → LstD