# Data sources
sources:
  # --- FM ---
  - name: "Försvarsmakten - Rikstäckande geodata"
    authority: "FM"
    type: "file"
    url: "https://www.forsvarsmakten.se/siteassets/2-om-forsvarsmakten/samhallsplanering/geodata/rikstackande-geodata-forsvarsmakten.zip"
    enabled: true

#--- NVV ---
  - name: "Naturvårdsverket - naturvådsregistret"
    authority: "NVV"
    type: "file"
    url: "https://geodata.naturvardsverket.se/nedladdning/naturvardsregistret/"
    enabled: true
    download_format: "zip"
    include: [
      Biosfarsomraden;
      DVO;
      HELCOM;
      IF;
      KR;
      LBSO;
      NP;
      NR;
      NVA;
      NVO;
      Nationalparksplan;
      OBO;
      OSPAR;
      Ramsar_2018;
      SCI_Rikstackande;
      SPA_Rikstackande;
      TILLTRADESFORBUD;
      VSO;
      Varldsarv
    ]

  # --- LST ---
  - name: "Miljöriskområde"
    authority: "LST"
    type: "atom_feed" # This tells the pipeline to use AtomFeedDownloadHandler
    url: "https://ext-dokument.lansstyrelsen.se/gemensamt/geodata/ATOM/ATOM_lst.LST_Miljoriskomrade.xml"
    staged_data_type: "gpkg" # Or "gpkg" if the Atom feed links *only* to GPKGs
                                            # If it links to ZIPs containing shapefiles, use "shapefile_collection"
                                            # If it links to a mix, the handler tries to infer per link.
                                            # This field helps the *loader* know what to expect in the staging dir.
    enabled: true
    # 'include' for atom_feed type is not used by this downloader version,
    # but could be used by the loader if the Atom feed stages multiple distinct GPKGs
    # into the source_specific_staging_dir. For now, assume all content from an Atom feed
    # is one logical dataset for that source.

  - authority: "LST"
    name: "Vindkraftskollen: Vindkraftverk"
    type: "atom_feed"
    url: "https://ext-dokument.lansstyrelsen.se/gemensamt/geodata/ATOM/ATOM_lst.vbk_vindkraftverk.xml"
    staged_data_type: "shapefile_collection"
    enabled: true
    BBOX: 


  - authority: "LST"
    name: "Vindkraftskollen: projekteringsområden"
    type: "atom_feed"
    url: "https://ext-dokument.lansstyrelsen.se/gemensamt/geodata/ATOM/ATOM_lst.vbk_projekteringsomraden.xml"
    enabled: true
    staged_data_type: "gpkg"

  - authority: "LST"
    name: "Potentiellt förorenade områden"
    type: "file"
    url: "https://ext-dokument.lansstyrelsen.se/Gemensamt/Geodata/Datadistribution/SWEREF99TM/EBH_Potentiellt_fororenade_omraden.zip"
    enabled: true
    staged_data_type: "shapefile_collection"

  - authority: "LST"
    name: "Riksintressen"
    type: "rest_api"
    url: "https://ext-geodata-nationella.lansstyrelsen.se/arcgis/rest/services/LST/lst_lst_riksintressen_4/MapServer"
    enabled: true
    staged_data_type: "json" # <--- IMPORTANT for the loader
    raw:
      format: "json" # Ensure handler outputs geojson

  - authority: "LST"
    name: "Riksintressen - Vindbruk"
    type: "rest_api"
    url: "https://ext-geodata-nationella.lansstyrelsen.se/arcgis/rest/services/LST/lst_lst_riksintressen_vindbruk_4/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
# --- LST ---
  - authority: "LST"
    name: "Riksintressen"
    type: "rest_api"
    url: "https://ext-geodata-nationella.lansstyrelsen.se/arcgis/rest/services/LST/lst_lst_riksintressen_4/MapServer"
    enabled: true
    staged_data_type: "geojson" # Change this to "geojson"
    raw:
      format: "geojson"       # Change this to "geojson"
      # layer_ids: [0, 1, 2, 3, 4, 5] # Optional: Omit to fetch all layers, or specify if needed

  - authority: "LST"
    name: "Riksintressen - Vindbruk"
    type: "rest_api"
    url: "https://ext-geodata-nationella.lansstyrelsen.se/arcgis/rest/services/LST/lst_lst_riksintressen_vindbruk_4/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
# --- LST ---
  - authority: "LSTD"
    name: "LstD Foreskrifter"
    type: "rest_api"
    url: "https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_Foreskrifter_EXT/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
  - authority: "LSTD"
    name: "LstD Fysisk planering"
    type: "rest_api"
    url: "https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_Fysisk_planering_EXT/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
  - authority: "LSTD"
    name: "LstD Ett rikt odlingslandskap"
    type: "rest_api"
    url: "https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_GI_Ett_rikt_odlingslandskap_EXT/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
      layer_ids: [2, 3, 4, 5, 6]      
  - authority: "LSTD"
    name: "LstD Friluftsliv"
    type: "rest_api"
    url: "https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_GI_Friluftsliv_EXT/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
      layer_ids: [0, 1, 2, 3, 4] # Optional: Omit to fetch all layers, or specify if needed

  - authority: "LSTD"
    name: "LstD God bebyggd miljö"
    type: "rest_api"
    url: "https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_GI_God_bebyggd_miljo_EXT/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
  - authority: "LSTD"
    name: "LstD Hav i balans"
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
    type: "rest_api"
    url: "https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_GI_Hav_i_balans_EXT/MapServer"
    enabled: true
  - authority: "LSTD"
    name: "LstD Levande sjöar och vattendrag"
    type: "rest_api"
    url: "https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_GI_Levande_sjoar_och_vattendrag_EXT/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
      layer_ids: [2, 3, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 ,17]      
  - authority: "LSTD"
    name: "LstD Levande skogar"
    type: "rest_api"
    url: "https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_GI_Levande_skogar_EXT/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
      layer_ids: [0]      
  - authority: "LSTD"
    name: "LstD Klimat"
    type: "rest_api"
    url: "https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_Klimat_EXT/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
      layer_ids: [2, 3, 4, 5, 6]
  - authority: "LSTD"
    name: "LstD Kulturmiljö"
    type: "rest_api"
    url: "https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_Kulturmiljo_EXT/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
      layer_ids: [1]     
  - authority: "LSTD"
    name: "LstD Markavvattning"
    type: "rest_api"
    url: "https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_Markavvattning_EXT/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" 
      layer_ids: [2, 3, 4, 5, 6]
  - authority: "LSTD"
    name: "LstD Markstabilitet"
    type: "rest_api"
    url: "https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_Markstabilitet_EXT/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
  - authority: "LSTD"
    name: "LstD Naturkartläggning"
    type: "rest_api"
    url: "https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_Naturkartlaggning_EXT/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
  - authority: "LSTD"
    name: "LstD Skog och träd"
    type: "rest_api"
    url: "https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_Skog_och_trad_EXT/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
  - authority: "LSTD"
    name: "LstD GI Värdetrakter våtmark"
    type: "rest_api"
    url: "https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_GI_Myllrande_vatmarker_EXT/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
  - authority: "LSTD"
    name: "LSTD Strandskydd"
    type: "rest_api"
    url: "https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_Strandskydd_EXT/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
# --- MSB ---
  - authority: "MSB"
    name: "Skyddsrum"
    type: "file"
    staged_data_type: "shapefile_collection"
    url: "https://inspire.msb.se/nedladdning/filer/shape/Skyddsrum.zip"
    enabled: true

# --- RAA ---
  - authority: "RAA"
    name: "Riksintresse Kulturmiljövård MB3kap6"
    type: "atom_feed"
    url: "https://ext-dokument.lansstyrelsen.se/gemensamt/geodata/ATOM/ATOM_raa.RAA_RI_kulturmiljovard_MB3kap6.xml"
    staged_data_type: "gpkg" # Or "gpkg"
    enabled: true
  - name: "RAA Byggnader Sverige" # This 'name' is used to create the staging subdir
    authority: "RAA"
    type: "file"                  # For the FileDownloadHandler
    url: "https://pub.raa.se/nedladdning/datauttag/bebyggelse/byggnader_kulthist_inv/byggnader_sverige.gpkg"
    download_format: "gpkg"     # Hint for downloader
    staged_data_type: "gpkg"  # Crucial for the ArcPyFileGDBLoader
    enabled: true
    include:
      - "byggnader_sverige_point" # Only attempt to load this valid layer
  - authority: "RAA"
    name: "Enskilda och statliga byggnadsminnen, skyddsområden"
    type: "file"
    url: "https://pub.raa.se/nedladdning/datauttag/bebyggelse/byggnadsminne_skyddsomr/skyddsomrade_byggnadsminne_sverige.gpkg"
    enabled: true
    download_format: "gpkg"
    staged_data_type: "gpkg"
    include:
      - "skyddsomrade_byggnadsminne_sverige_polygon"
  - authority: "RAA"
    name: "Kulturhistoriska lämningar, Södermanland"
    type: "file"
    url: "https://pub.raa.se/nedladdning/datauttag/lamningar/lan/l%C3%A4mningar_l%C3%A4n_s%C3%B6dermanland.gpkg"
    enabled: true
    download_format: "gpkg"
    staged_data_type: "gpkg"
  - name: "RAA Världsarv i Sverige"
    authority: "RAA"
    type: "file"
    url: "https://pub.raa.se/nedladdning/datauttag/varldsarv/varldsarv_sverige.gpkg"
    download_format: "gpkg"
    staged_data_type: "gpkg"
    enabled: true
    include:
      - "varldsarv_sverige_polygon" # Only attempt to load this valid layer
      
# --- SGI ---
  - authority: "SGI"
    name: "Inträffade skred, ras och övriga jordrörelser (skreddatabas)"
    type: "file"
    url: "https://gis.sgi.se/dokument/geodatasezip/SGI_Skreddatabas_ver2.zip"
    enabled: true

# --- SGU ---
# Data sources
  - authority: "SGU"
    name: "Erosion"
    type: "ogc_api"
    url: "https://api.sgu.se/oppnadata/stranderosion-kust/ogc/features/v1/collections/"
    enabled: true
    staged_data_type: "geojson"
    raw:
      collections: ["aktiv-erosion"]
      page_size: 1000

  - authority: "SGU"
    name: "Brunnar"
    type: "ogc_api"
    url: "https://api.sgu.se/oppnadata/brunnar/ogc/features/v1/collections/"
    enabled: true
    staged_data_type: "geojson"
    raw:
      collections: ["brunnar"]
      page_size: 1000

  - authority: "SGU"
    name: "Jordskred och raviner"
    type: "ogc_api"
    url: "https://api.sgu.se/oppnadata/jordskred-raviner/ogc/features/v1/collections/"
    enabled: true
    staged_data_type: "geojson"
    raw:
      collections: ["jordskred-raviner"]
      page_size: 1000

  - authority: "SGU"
    name: "Grus Krossberg"
    type: "ogc_api"
    url: "https://api.sgu.se/oppnadata/grus-krossberg/ogc/features/v1/collections"
    enabled: true
    staged_data_type: "geojson"
    raw:
      collections: ["grus-grus", "grus-berg", "grus-moran"]
      page_size: 1000


  # # --- SJV ---
  - authority: "SJV"
    name: "Jordbruksblock (2024)"
    type: "rest_api"
    url: "https://ext-geodata-nationella.lansstyrelsen.se/arcgis/rest/services/SJV/lst_sjv_fak04jbb/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
      layer_ids: [18]

  - authority: "SJV"
    name: "Jordbruksskiften (senaste året)"
    type: "rest_api"
    url: "https://epub.sjv.se/inspire/inspire/wfs"
    enabled: false
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
      layer_ids: [18] 

  - authority: "SJV"
    name: "Produktionsplatser för djurhållning"
    type: "file"
    url: "http://epub.sjv.se/inspire/inspire/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=inspire:produktionsplatser&outputFormat=application/json"
    enabled: true
    staged_data_type: "geojson"
    download_format: "json"

  - authority: "SJV"
    name: "Ängs- och betesmarksinventeringen"
    type: "rest_api"
    url: "https://ext-geodata-nationella.lansstyrelsen.se/arcgis/rest/services/SJV/lst_sjv_fak04ovr/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
      layer_ids: [4, 5] 

  # --- SKS ---
  - authority: "SKS"
    name: "Naturvärden"
    type: "file"
    url: "https://geodpags.skogsstyrelsen.se/geodataport/data/sksNaturvarden_gpkg.zip"
    enabled: true
    staged_data_type: "gpkg" 

  - authority: "SKS"
    name: "Ras och skred"
    type: "atom_feed"
    url: "https://geodpags.skogsstyrelsen.se/geodataport/feeds/Rasochskred.xml"
    enabled: true
  - name: "Skogsstyrelsen - Biotopskydd (REST)"
    authority: "SKS"
    type: "rest_api"
    url: "https://geodpags.skogsstyrelsen.se/arcgis/rest/services/Geodataportal/GeodataportalVisaBiotopskydd/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
  - authority: "SKS"
    name: "Utförda avverkningar"
    type: "rest_api"
    url: "https://geodpags.skogsstyrelsen.se/arcgis/rest/services/Geodataportal/GeodataportalVisaUtfordavverkning/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
  - authority: "SKS"
    name: "Naturvårdsavtal"
    type: "rest_api"
    url: "https://geodpags.skogsstyrelsen.se/arcgis/rest/services/Geodataportal/GeodataportalVisaNaturvardsavtal/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
  - authority: "SKS"
    name: "Återvätningsavtal"
    type: "rest_api"
    url: "https://geodpags.skogsstyrelsen.se/arcgis/rest/services/Geodataportal/GeodataportalVisaAtervatningavtal/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
  - authority: "SKS"
    name: "Nyckelbiotoper"
    type: "rest_api"
    url: "https://geodpags.skogsstyrelsen.se/arcgis/rest/services/Geodataportal/GeodataportalVisaNyckelbiotop/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
  - authority: "SKS"
    name: "Sumpskogar"
    type: "rest_api"
    url: "https://geodpags.skogsstyrelsen.se/arcgis/rest/services/Geodataportal/GeodataportalVisaSumpskog/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
  - authority: "SKS"
    name: "Avverkningsanmälda områden"
    type: "rest_api"
    url: "https://geodpags.skogsstyrelsen.se/arcgis/rest/services/Geodataportal/GeodataportalVisaAvverkningsanmalan/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
  - authority: "SKS"
    name: "Gräns för skogsskyddsbestämmelser"
    type: "rest_api"
    url: "https://geodpags.skogsstyrelsen.se/arcgis/rest/services/Geodataportal/GeodataportalVisaSkogsskyddsbestammelser/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson
  - authority: "SKS"
    name: "Nyckelbiotoper - storskogsbruket"
    type: "rest_api"
    url: "https://geodpags.skogsstyrelsen.se/arcgis/rest/services/Geodataportal/GeodataportalVisaSkogsbruknyckelbiotop/MapServer"
    enabled: true
    staged_data_type: "geojson" # <--- IMPORTANT for the loader
    raw:
      format: "geojson" # Ensure handler outputs geojson

  # --- SVK ---
  - authority: "SVK"
    name: "Stamnät"
    type: "file"
    url: "https://gis-services.metria.se/svkfeed/filer/SVK_STAMNAT.zip"
    enabled: true