name: Basic validation

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  basic-validation:
    name: Basic validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check Python syntax
        run: |
          python -m py_compile **/*.py || echo "No Python files found"

      - name: Validate YAML files
        run: |
          python -c "
          import yaml
          import glob
          import sys
          
          yaml_files = glob.glob('**/*.yml', recursive=True) + glob.glob('**/*.yaml', recursive=True)
          
          if not yaml_files:
              print('No YAML files found')
              sys.exit(0)
          
          errors = []
          for file in yaml_files:
              try:
                  with open(file, 'r') as f:
                      yaml.safe_load(f)
                  print(f'✓ {file}')
              except Exception as e:
                  errors.append(f'✗ {file}: {e}')
          
          if errors:
              for error in errors:
                  print(error)
              sys.exit(1)
          else:
              print('All YAML files are valid')
          "

      - name: Check for common issues
        run: |
          echo "Checking for common issues..."
          
          # Check for merge conflict markers
          if grep -r "<<<<<<< HEAD" . --exclude-dir=.git; then
            echo "Error: Merge conflict markers found"
            exit 1
          fi
          
          # Check for TODO/FIXME comments
          if find . -name "*.py" -exec grep -l "TODO\|FIXME" {} \; | head -5; then
            echo "Warning: TODO/FIXME comments found (not blocking)"
          fi
          
          echo "Basic validation completed successfully"
